FROM node:24-alpine AS build
WORKDIR /app
COPY frontend/hrms-web/package*.json ./
RUN npm ci --silent
COPY frontend/hrms-web ./
RUN npm run build --silent

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
