FROM mcr.microsoft.com/dotnet/sdk:10 AS build
WORKDIR /src
COPY . ./
RUN dotnet publish src/HRMS.Api -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10
WORKDIR /app
COPY --from=build /app/publish ./
EXPOSE 5000
ENTRYPOINT ["dotnet", "HRMS.Api.dll"]
